import Root from './components/Root'
import './App.css';
import Items from './components/Items';
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Error from "./components/Error";
import HomeDetails from './components/HomeDetails';
import "react-datepicker/dist/react-datepicker.css"


function App() {

  const items = [
  {id:1, image: ['https://img.staticmb.com/mbcontent//images/uploads/2022/12/Most-Beautiful-House-in-the-World.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg', 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmVkcm9vbXxlbnwwfHwwfHw%3D&w=1000&q=80'], location: 'barcelona', price: 123.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:2, image: ['https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://www.bhg.com/thmb/dgy0b4w_W0oUJUxc7M4w3H4AyDo=/1866x0/filters:no_upscale():strip_icc()/living-room-gallery-shelves-l-shaped-couch-ELeyNpyyqpZ8hosOG3EG1X-b5a39646574544e8a75f2961332cd89a.jpg'], location: 'valencia', price: 76, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:3, image: ['https://img.staticmb.com/mbcontent//images/uploads/2022/5/modern-kerala-house-design.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 198.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:4, image: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?cs=srgb&dl=pexels-binyamin-mellish-106399.jpg&fm=jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'baku', price: 143.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:5, image: ['https://s42814.pcdn.co/wp-content/uploads/2020/09/iStock_185930591-scaled.jpg.optimal.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'paris', price: 543.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:6, image: ['https://www.buildofy.com/blog/content/images/2022/06/_DSC9610-Edited_-min.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 93.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:7, image: ['https://b3004696.smushcdn.com/3004696/wp-content/uploads/2021/04/DEEPDENE-MODERN-HOUSE-1.jpg?lossy=1&strip=1&webp=1','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:8, image: ['https://www.pexels.com/photo/1029599/download/','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:9, image: ['https://img.staticmb.com/mbcontent//images/uploads/2022/12/Most-Beautiful-House-in-the-World.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 123.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:10, image: ['https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'valencia', price: 76, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:11, image: ['https://img.staticmb.com/mbcontent//images/uploads/2022/5/modern-kerala-house-design.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 198.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:12, image: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?cs=srgb&dl=pexels-binyamin-mellish-106399.jpg&fm=jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'baku', price: 143.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:13, image: ['https://s42814.pcdn.co/wp-content/uploads/2020/09/iStock_185930591-scaled.jpg.optimal.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'paris', price: 543.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:14, image: ['https://www.buildofy.com/blog/content/images/2022/06/_DSC9610-Edited_-min.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 93.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:15, image: ['https://b3004696.smushcdn.com/3004696/wp-content/uploads/2021/04/DEEPDENE-MODERN-HOUSE-1.jpg?lossy=1&strip=1&webp=1','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:16, image: ['https://www.pexels.com/photo/1029599/download/','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:17, image: ['https://img.staticmb.com/mbcontent//images/uploads/2022/5/modern-kerala-house-design.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 198.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:18, image: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?cs=srgb&dl=pexels-binyamin-mellish-106399.jpg&fm=jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'baku', price: 143.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:19, image: ['https://s42814.pcdn.co/wp-content/uploads/2020/09/iStock_185930591-scaled.jpg.optimal.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'paris', price: 543.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:20, image: ['https://www.buildofy.com/blog/content/images/2022/06/_DSC9610-Edited_-min.jpg','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 93.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:21, image: ['https://b3004696.smushcdn.com/3004696/wp-content/uploads/2021/04/DEEPDENE-MODERN-HOUSE-1.jpg?lossy=1&strip=1&webp=1','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'],location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
  {id:22, image: ['https://www.pexels.com/photo/1029599/download/','https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939__340.jpg','https://hips.hearstapps.com/hmg-prod/images/1-alec-holland-hamptons-house-1661876383.jpg'], location: 'barcelona', price: 343.98, description: 'Junto a la playa de Puerto Blanco se encuentra un bonito y pequeño castillo español, Villa Ronda. Desplegándose a través de tres plantas separadas, cada una de ellas con su propia sala de estar y su cocina, sin mencionar la amplitud de un total de 6 habitaciones y 7 cuartos de baño, Villa Ronda es la elección perfecta tanto para familias como para grupos de amigos que viajan juntos.Un cuento de hadas como una torreta que se eleva por encima del resto, Villa Ronda...'},
]

const router = createBrowserRouter([
  {
    path: '/',
    element: <Root />,
    errorElement: <Error />,
    children: [
      {index: true, element: <Items items = {items}/>},
      {path: '/product/:id', element: <HomeDetails items = {items}/>}
    ]
  }
])
  return (
    <RouterProvider router={router} className='App' />
  )
}

export default App;
